apiVersion: v1
kind: Pod
metadata:
  name: seltest
  labels:
    app: seltest
spec:
  containers:
  - name: app
    image: ssasso/simple:2
    ports:
      - containerPort: 8080
  nodeSelector:
    kubernetes.io/hostname: k-worker-3

