apiVersion: v1
kind: Service
metadata:
  name: {{ include "zoo.fullname" . }}
  labels:
{{ include "zoo.labels" . | indent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "zoo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
