apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: fibonacci-hpa
spec:
    minReplicas: 2
    maxReplicas: 8
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: fibonacci
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
            type: Utilization
            averageUtilization: 10

