kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.247.16.0/20"
  serviceSubnet: "10.247.32.0/20"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker

