apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mycni
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "MYCNI",
      "ptp_address": "169.254.250.250"
    }'

