#!/bin/bash

# DEPENDENCIES
# - kubectl
# - curl
# - jq

# We need to be very careful with stdout because kubernetes wants valid json
# So we going to save it
exec 6>&1

# and replace stdout with logfile
LOGFILE=/tmp/my-cni.log
exec &>> $LOGFILE

# functions
# -- Helpers
get_pod            () { while read line; do [[ ${line/=*/} == "K8S_POD_NAME" ]] && echo ${line/*=/} || :; done; }
get_pod_ns         () { while read line; do [[ ${line/=*/} == "K8S_POD_NAMESPACE" ]] && echo ${line/*=/} || :; done; }
get_tenant         () { while read line; do [[ ${line/=*/} == "owner" ]] && echo ${line/*=/} || :; done; }
get_json_kv        () { sed 's/["{}]//g' | xargs -d "," -n1; }
get_nspid          () { echo $1 | awk -F"/" '{ print $3 }'; }
get_ip             () { while read line; do [[ ${line/:*/} == "ip" ]] && echo ${line/*:/} || :; done; }
get_args           () { echo $CNI_ARGS | xargs -d";" -n1 ;}
get_config_item    () { echo $INPUT | jq -r ".${1}"; }
log                () { echo "$*"; }
log_env            () { env; }

die () {
    echo $1
    # Restore stdout - before reporting an error to Kube
    exec 1>&6

    printf '{ "Error": "%s" }' "$1"
    exit $2
}

trap "die 'CNI plugin - Unexpected error'" EXIT

# -- Config
# Kubernetes pases config via stdin
INPUT=`cat /dev/stdin`

log "Started"
log "COMMAND: $CNI_COMMAND"
log "ENV [begin]"
log_env
log "ENV [end]"
log "INPUT [begin]"
log $INPUT
log "INPUT [end]"

case $CNI_COMMAND in
ADD)
    mkdir -p /var/run/netns/
    ln -sfT $CNI_NETNS /var/run/netns/$CNI_CONTAINERID
    log "--- ADD --"
    log "--- CNI_CONTAINERID = $CNI_CONTAINERID ---"
    POD=$(get_args | get_pod)
    log "--- POD = $POD ---"
    NAMESPACE=$(get_args | get_pod_ns)
    log "--- NAMESPACE = $NAMESPACE ---"
    NSPID=$(get_nspid "$CNI_NETNS")
    log "--- NSPID = $NSPID ---"
    API_URL=$(get_config_item api_url)
    API_CERT=$(get_config_item api_cert)
    URL="$API_URL/api/v1/namespaces/$NAMESPACE/pods/$POD"
    log "--- URL = $URL ---"
    POD_DATA=$(curl -s --cacert /etc/kubernetes/ssl/ca.crt --cert $API_CERT $URL)
    log "POD_DATA [begin]"
    log $POD_DATA
    log "POD_DATA [end]"
    IP=$(echo -n $POD_DATA | jq -r 'if .metadata.annotations."my.cni/ip" then .metadata.annotations."my.cni/ip" else empty end')
    log "--- StaticIP = $IP ---"
    if [ -z $IP ]; then
	    die "Unable to allocate IP. Exiting" 1
    fi
    ITABLE=$(echo -n $POD_DATA | jq -r 'if .metadata.annotations."my.cni/itable" then .metadata.annotations."my.cni/itable" else empty end')
    [ -z $ITABLE ] && ITABLE=100
    log "--- iTable = $ITABLE ---"
    PTPADDR=$(get_config_item ptp_address)
    log "--- PTP = $PTPADDR ---"
    log "--- CNI_IFNAME = $CNI_IFNAME ---"

    log "--- HOST IFACE = v-${NSPID} ---"

    # Setting up the networking
    # Creating vETH pair
    ip link add "v-${NSPID}" type veth peer name "${CNI_IFNAME}"
    # Set container stuf
    ip link set "${CNI_IFNAME}" netns ${CNI_CONTAINERID}
    ip netns exec $CNI_CONTAINERID ip link set lo up
    ip netns exec $CNI_CONTAINERID ip link set $CNI_IFNAME up
    ip netns exec $CNI_CONTAINERID ip addr add $IP peer $PTPADDR dev $CNI_IFNAME
    ip netns exec $CNI_CONTAINERID ip route add $PTPADDR dev $CNI_IFNAME scope link src $IP table $ITABLE
    ip netns exec $CNI_CONTAINERID ip route add default via $PTPADDR table $ITABLE
    ip netns exec $CNI_CONTAINERID ip rule add pref ${ITABLE}1 from $IP lookup $ITABLE
    ip netns exec $CNI_CONTAINERID ip rule add pref ${ITABLE}2 from $IP blackhole
    ip netns exec $CNI_CONTAINERID ip rule add pref ${ITABLE}9 iif $CNI_IFNAME blackhole
    # Set host stuff
    # Create custom VRF if not present, and add interface
    # TODO
    # Add IP
    ip addr add $PTPADDR peer $IP dev v-${NSPID}
    ip link set "v-${NSPID}" up

    mac=$(ip netns exec $CNI_CONTAINERID ip link show $CNI_IFNAME | awk '/ether/ {print $2}')
    address="${IP}/32"
    output="{
  \"cniVersion\": \"0.3.1\",
  \"interfaces\": [                                            
      {
          \"name\": \"${CNI_IFNAME}\",
          \"mac\": \"${mac}\",                            
          \"sandbox\": \"${CNI_NETNS}\" 
      }
  ],
  \"ips\": [
      {
          \"version\": \"4\",
          \"address\": \"${address}\",
          \"interface\": 0 
      }
  ]
}"
    log "----- OUTPUT -----"
    log $output
    # Restore stdout - ready to talk back to kubernetes
    exec 1>&6
    echo -n $output
    
;;

DEL)
    rm -rf /var/run/netns/$CNI_CONTAINERID || e=1
    exec 1>&6
;;

GET)
;;

VERSION)
echo '{
  "cniVersion": "0.3.1", 
  "supportedVersions": [ "0.3.0", "0.3.1", "0.4.0" ] 
}'
;;

*)
  echo "Unknown cni command: $CNI_COMMAND" 
  exit 1
;;

esac
# normal exit shouldn't trigger trap
trap - EXIT

